// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeLogger.Infrastructure.Persistence;

#nullable disable

namespace TimeLogger.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220083741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeLogger.Domain.Entities.ImportSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PollSchedule")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImportSources");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.ImportedEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ImportSourceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IssueKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MappingRuleId")
                        .HasColumnType("int");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("TimelogProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TimelogTaskId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MappingRuleId");

                    b.HasIndex("TimelogProjectId");

                    b.HasIndex("TimelogTaskId");

                    b.HasIndex("ImportSourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("ImportedEntries");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.MappingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MatchField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MatchOperator")
                        .HasColumnType("int");

                    b.Property<string>("MatchValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("TimelogProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TimelogTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimelogProjectId");

                    b.HasIndex("TimelogTaskId");

                    b.ToTable("MappingRules");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.SubmittedEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ImportedEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ImportedEntryId")
                        .IsUnique();

                    b.ToTable("SubmittedEntries");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.TimelogProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("TimelogProjects");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.TimelogTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TimelogProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimelogProjectId", "ExternalId")
                        .IsUnique();

                    b.ToTable("TimelogTasks");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.ImportedEntry", b =>
                {
                    b.HasOne("TimeLogger.Domain.Entities.ImportSource", "ImportSource")
                        .WithMany("ImportedEntries")
                        .HasForeignKey("ImportSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeLogger.Domain.Entities.MappingRule", "MappingRule")
                        .WithMany("MatchedEntries")
                        .HasForeignKey("MappingRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeLogger.Domain.Entities.TimelogProject", "TimelogProject")
                        .WithMany("ImportedEntries")
                        .HasForeignKey("TimelogProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeLogger.Domain.Entities.TimelogTask", "TimelogTask")
                        .WithMany("ImportedEntries")
                        .HasForeignKey("TimelogTaskId");

                    b.Navigation("ImportSource");

                    b.Navigation("MappingRule");

                    b.Navigation("TimelogProject");

                    b.Navigation("TimelogTask");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.MappingRule", b =>
                {
                    b.HasOne("TimeLogger.Domain.Entities.TimelogProject", "TimelogProject")
                        .WithMany("MappingRules")
                        .HasForeignKey("TimelogProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeLogger.Domain.Entities.TimelogTask", "TimelogTask")
                        .WithMany("MappingRules")
                        .HasForeignKey("TimelogTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TimelogProject");

                    b.Navigation("TimelogTask");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.SubmittedEntry", b =>
                {
                    b.HasOne("TimeLogger.Domain.Entities.ImportedEntry", "ImportedEntry")
                        .WithOne("SubmittedEntry")
                        .HasForeignKey("TimeLogger.Domain.Entities.SubmittedEntry", "ImportedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedEntry");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.TimelogTask", b =>
                {
                    b.HasOne("TimeLogger.Domain.Entities.TimelogProject", "TimelogProject")
                        .WithMany("Tasks")
                        .HasForeignKey("TimelogProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimelogProject");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.ImportSource", b =>
                {
                    b.Navigation("ImportedEntries");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.ImportedEntry", b =>
                {
                    b.Navigation("SubmittedEntry");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.MappingRule", b =>
                {
                    b.Navigation("MatchedEntries");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.TimelogProject", b =>
                {
                    b.Navigation("ImportedEntries");

                    b.Navigation("MappingRules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TimeLogger.Domain.Entities.TimelogTask", b =>
                {
                    b.Navigation("ImportedEntries");

                    b.Navigation("MappingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
